[connection]

[[connection.influxdb]]
name = "Influx1.8 SSD" 
default = true 
url = "http://127.0.0.1:18086" 
user = "" 
pass = "" 
db = "stress" # Database that will be written to
tls-skip-verify = false # Skip verify in for TLS
rp = "" # Retention Policy that will be written to
precision = "n" # Resolution of data being written
consistency = "one" # Write consistency (only applicable to clusters)
gzip = -1 # If non-zero, gzip write bodies with given compression level. 1=best speed, 9=best compression, -1=gzip default.

[[connection.influxdb]]
name = "Influx1.8 HDD" 
default = false 
url = "http://127.0.0.1:28086" 
user = "" 
pass = "" 
db = "stress" # Database that will be written to
tls-skip-verify = false # Skip verify in for TLS
rp = "" # Retention Policy that will be written to
precision = "n" # Resolution of data being written
consistency = "one" # Write consistency (only applicable to clusters)
gzip = -1 # If non-zero, gzip write bodies with given compression level. 1=best speed, 9=best compression, -1=gzip default.

[[connection.mysql]]
name = "MySQL8 SSD"
default = true
host = "127.0.0.1:13308"
user = "root"
pass = "docker"
db = "stress"

[[connection.mysql]]
name = "MySQL8 HDD"
default = false
host = "127.0.0.1:23308"
user = "root"
pass = "docker"
db = "stress"

[points]
measurement = "ctr"
series-key = "some=tag,other=tag"
fields-str = "n=0i,data=str,log=str"


# pending cases to run
[cases]

delay = "5s" # delay between cases

[[cases.case]]
name = "Influx SSD"
connection = "Influx1.8 SSD"
concurrent = 20
batch-size = 10000
runtime = "30s"

[[cases.case]]
name = "Influx HDD"
connection = "Influx1.8 HDD"
concurrent = 20
batch-size = 10000
runtime = "30s"

[[cases.case]]
name = "MySQL SSD"
connection = "MySQL8 SSD"
concurrent = 20
batch-size = 10000
runtime = "30s"

[[cases.case]]
name = "MySQL HDD"
connection = "MySQL8 HDD"
concurrent = 20
batch-size = 10000
runtime = "30s"
